services:
  mysql-8:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "orders"
    ports:
      - "3307:3307"
  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBIT_DEFAULT_USER=rabbitmq
      - RABBIT_DEFAULT_PASSWORD=rabbitmq