services:
  postgres:
    container_name: postgresql_db
    image: postgres:12.8
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=local
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - MAX_CONNECTIONS=300
  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq