spring:
  datasource:
    username: local
    url: jdbc:postgresql://localhost:5432/local?currentSchema=order_service_db_postgresql
    password: local
  jpa:
    show-sql: 'true'

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq